default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: man
  password: 1042107
  port: 5432
  pool: <%= ENV['RAILS_MAX_THREADS'] || 5 %>

development:
  <<: *default
  database: alistar_be_dev

test:
  <<: *default
  database: alistar_be_test
